<?php echo $this->doctype('XHTML1_STRICT');?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php //echo $this->headLink()->prependStylesheet("/zend/public/css/main.css");?>
        <?php $this->headLink()->appendStylesheet(
                $this->baseUrl().'/css/blueprint/screen.css', 'screen'
        );?>
        <?php $this->headLink()->appendStylesheet(
                $this->baseUrl().'/css/blueprint/print.css', 'print'
        );?>  
        <?php $this->headLink()->appendStylesheet(
                $this->baseUrl().'/css/blueprint/ie.css', 'screen','IE'
        );?>
        <?php $this->headLink()->appendStylesheet(
                $this->baseUrl().'/css/blueprint/master.css', 'screen'
        );?>
        <?php echo $this->headLink();?>
    </head>
    <body>
        <div class="container">
            <div id="header" class="span-24 last">
                <h2>Header</h2>
            </div>
            <div id="content" class="span-17 colborder">
                <?php echo $this->layout()->content;?>
            </div>
            <div id="sidebar" class="span-6 last">
                <p>Sidebar</p>
            </div>
            <div id="footer" class="span-24 last">
               <p>Footer</p> 
            </div>
        </div>    
    </body>    
</html>    