<?php if(count($this->users)):?>
    <table>
        <tr>
            <th>ID</th>
            <th>Логин</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Email</th>
            <th>Активирован</th>
            <th>Операция</th>
        </tr>
    <?php foreach ($this->users as $user) : ?>
        <tr>
            <td><?php echo $user->id; ?></td>
            <td><a href="<?php echo $this->url(array(
                    'controller' => 'users',
                    'action' => 'view',
                    'id' => $user->id
                )); ?>"> <?php echo $user->username; ?></a>
               </td>
            <td><a href="<?php echo $this->url(array(
                    'controller' => 'users',
                    'action' => 'view',
                    'id' => $user->id
                )); ?>"> <?php echo $user->name; ?></a>
            </td>   
            <td><a href="<?php echo $this->url(array(
                    'controller' => 'users',
                    'action' => 'view',
                    'id' => $user->id
                )); ?>"> <?php echo $user->surname; ?></a>
            </td>   
            <td><?php echo $user->email; ?></td>
            <td><?php  echo ($user->activated) ?  "да" :  "нет";  ?></td>
            
            <td>
                <a href="<?php echo $this->url(array(
                    'controller' => 'users',
                    'action' => 'edit',
                    'id' => $user->id
                )); ?>">Edit</a>
                <a href="<?php echo $this->url(array(
                    'controller' => 'users',
                    'action' => 'delete',
                    'id' => $user->id
                )); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach;?>
    </table>    
<?php else:?>
    <p>Пользователей пока нет.</p>
<?php endif; ?>

    <a href="<?php echo $this->url(array(
        'controller' => 'users',
        'action' => 'add'
    )); ?>" title="">Добавить нового пользователя</a>
